spring:
  application:
    name: RazorPay
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/razorpayDB}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:Up2date}
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

vault:
  master-key: xrMeaevLX3tO590sZ3FVXqkA/XAA+1WDLLe0K2m606Q=

payment:
  simulator:
    poll-interval-ms: 5000
    chaos-mode: NORMAL
    method:
      CARD:
        min-delay-seconds: 2
        max-delay-seconds: 6
        success-rate: 90
      UPI:
        min-delay-seconds: 1
        max-delay-seconds: 2
        success-rate: 95
      NET_BANKING:
        min-delay-seconds: 4
        max-delay-seconds: 10
        success-rate: 80

jwt:
  secret-key: don't_use_in_prod_HRIl6_oijmck2B6j3-Z04QhtXvv_GUr0FQs4Mz8lSrg